clear;
closeall;

main_dir = pwd;

sim_name = 'spiral_outcoupler';
folder = 'SIM02_'+ sim_name;
details = 'charge';
for (j=[-1,0,2]) {
    filename = folder +'/'+ sim_name + details + num2str(j) +'.fsp' ;
    load(filename);
    run;
    cd(main_dir);
    system("powershell -c [console]::beep(500,500)"); # valid for windows only ([Hz],[ms])
}

    system("powershell -c [console]::beep(500,5000)"); # valid for windows only ([Hz],[ms])
